Repository Kuadrant/wasm-shim, pull requests merged in 2024-10, with the labels that each got.

#92 External Auth ~ish
  Makefile
  README.md
  make/deploy.mk
  src/attribute.rs
  src/configuration.rs
  src/envoy/mod.rs
  src/filter/http_context.rs
  src/filter/root_context.rs
  src/lib.rs
  src/operation_dispatcher.rs
  src/policy.rs
  src/policy_index.rs
  src/service.rs
  src/service/auth.rs
  src/service/grpc_message.rs
  src/service/rate_limit.rs
  tests/rate_limited.rs
  utils/deploy/authconfig.yaml
  utils/deploy/envoy-notls.yaml
  utils/deploy/envoy-tls.yaml
  utils/deploy/limitador.yaml
  utils/docker-compose/limits.yaml
  utils/kind/cluster.yaml
Labels: enhancement, size/medium, target/current

#94 version bump to 0.7.0-dev
  Cargo.lock
  Cargo.toml
Labels: enhancement

#111 source.remote_address well known attribute
  .github/workflows/e2e.yaml
  README.md
  e2e/remote-address/Makefile
  e2e/remote-address/README.md
  e2e/remote-address/docker-compose.yaml
  e2e/remote-address/envoy.yaml
  e2e/remote-address/limits.yaml
  src/attribute.rs
  src/configuration.rs
  src/lib.rs
  src/policy.rs
  src/property.rs
  src/property_path.rs
  tests/auth.rs
  tests/multi.rs
  tests/rate_limited.rs
  tests/remote_address.rs
  utils/deploy/envoy-notls.yaml
  utils/deploy/envoy-tls.yaml
  utils/deploy/limits.yaml
Labels: enhancement, size/medium

#113 Predicate on our "well-known attributes"
  README.md
  src/configuration.rs
  src/configuration/action.rs
  src/configuration/action_set.rs
  src/data/attribute.rs
  src/data/cel.rs
  src/data/mod.rs
  src/data/property.rs
  src/filter/http_context.rs
  src/lib.rs
  src/operation_dispatcher.rs
  src/property.rs
  src/property_path.rs
  src/service/auth.rs
  tests/auth.rs
  tests/multi.rs
  tests/rate_limited.rs
  tests/remote_address.rs
Labels: enhancement
